import { ApiProperty } from '@nestjs/swagger';
import { IsUUID, IsDateString, IsOptional, IsString, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

export class MusterRollEntryDto {
  @ApiProperty({
    description: 'Employee ID',
    example: '123e4567-e89b-12d3-a456-426614174000'
  })
  @IsUUID()
  employeeId: string;

  @ApiProperty({
    description: 'Employee name',
    example: 'John Smith'
  })
  @IsString()
  employeeName: string;

  @ApiProperty({
    description: 'Employee number',
    example: 'EMP001'
  })
  @IsString()
  employeeNumber: string;

  @ApiProperty({
    description: 'Site ID where employee is assigned',
    example: '123e4567-e89b-12d3-a456-426614174001'
  })
  @IsUUID()
  siteId: string;

  @ApiProperty({
    description: 'Site name',
    example: 'Central Mall - Main Entrance'
  })
  @IsString()
  siteName: string;

  @ApiProperty({
    description: 'Client name',
    example: 'Central Shopping Mall'
  })
  @IsString()
  clientName: string;

  @ApiProperty({
    description: 'Assigned role',
    example: 'Security Guard'
  })
  @IsString()
  role: string;

  @ApiProperty({
    description: 'Shift start time',
    example: '08:00'
  })
  @IsString()
  shiftStart: string;

  @ApiProperty({
    description: 'Shift end time',
    example: '16:00'
  })
  @IsString()
  shiftEnd: string;

  @ApiProperty({
    description: 'Employee contact number',
    example: '+1234567890'
  })
  @IsString()
  contactNumber: string;

  @ApiProperty({
    description: 'Emergency contact number',
    example: '+1234567891'
  })
  @IsString()
  emergencyContact: string;

  @ApiProperty({
    description: 'Special responsibilities or notes',
    example: 'Access control, visitor registration'
  })
  @IsOptional()
  @IsString()
  responsibilities?: string;

  @ApiProperty({
    description: 'Current status',
    example: 'on-duty',
    enum: ['scheduled', 'on-duty', 'absent', 'late']
  })
  @IsString()
  status: string;
}

export class GenerateMusterRollDto {
  @ApiProperty({
    description: 'Date for the muster roll',
    example: '2024-01-15'
  })
  @IsDateString()
  date: string;

  @ApiProperty({
    description: 'Optional site ID filter',
    example: '123e4567-e89b-12d3-a456-426614174001',
    required: false
  })
  @IsOptional()
  @IsUUID()
  siteId?: string;

  @ApiProperty({
    description: 'Optional client ID filter',
    example: '123e4567-e89b-12d3-a456-426614174002',
    required: false
  })
  @IsOptional()
  @IsUUID()
  clientId?: string;

  @ApiProperty({
    description: 'Export format',
    example: 'pdf',
    enum: ['pdf', 'excel', 'csv'],
    required: false
  })
  @IsOptional()
  @IsString()
  format?: 'pdf' | 'excel' | 'csv';
}

export class MusterRollDto {
  @ApiProperty({
    description: 'Muster roll ID',
    example: '123e4567-e89b-12d3-a456-426614174003'
  })
  @IsUUID()
  id: string;

  @ApiProperty({
    description: 'Date of the muster roll',
    example: '2024-01-15'
  })
  @IsDateString()
  date: string;

  @ApiProperty({
    description: 'Generation timestamp',
    example: '2024-01-15T08:00:00Z'
  })
  @IsDateString()
  generatedAt: string;

  @ApiProperty({
    description: 'Generated by user ID',
    example: '123e4567-e89b-12d3-a456-426614174004'
  })
  @IsUUID()
  generatedBy: string;

  @ApiProperty({
    description: 'Total number of deployed guards',
    example: 45
  })
  totalGuards: number;

  @ApiProperty({
    description: 'Number of sites covered',
    example: 12
  })
  totalSites: number;

  @ApiProperty({
    description: 'Number of clients served',
    example: 8
  })
  totalClients: number;

  @ApiProperty({
    description: 'Muster roll entries',
    type: [MusterRollEntryDto]
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => MusterRollEntryDto)
  entries: MusterRollEntryDto[];

  @ApiProperty({
    description: 'Summary statistics',
    example: {
      onDuty: 42,
      scheduled: 3,
      absent: 0,
      late: 0
    }
  })
  summary: {
    onDuty: number;
    scheduled: number;
    absent: number;
    late: number;
  };
}